/// <reference types= "cypress" />

import { SigninPage } from "../PageObject/PageAction/SigninPage";
import { AdditionalCurrencies } from "../PageObject/PageAction/AdditionalCurrencies";

const signin = new SigninPage
const newRecipient = new AdditionalCurrencies

describe('Additional Currencies ',function(){

    let userName = 'testnew@volopa.com'
    let password = 'testTest1'
    beforeEach(function(){
        cy.visit('https://webapp3.volopa.com/')
        cy.viewport(1440,1000)
    })
    // Currency is SGD
    it('TC-AC-001 - Verify that if Currency= SGD and Country = UNITED KINGDOM & client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SGD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('tester SGD')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-002 - Verify that if Currency= SGD and Country = SINGAPORE  & Client = UK with the limit of 200,000 SGD Maximum per payment and check priority and regular both settlement are enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SINGAPORE{enter}' ,'SGD{enter}')
        newRecipient.addBankDetailsWithAccNo('ACLPSGSG','049712')
        newRecipient.individualRecipient('QA Tester SGD')
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('200001','Maximum limit for SGD is 200,000.00')
        newRecipient.checkSettelmentEnabledBoth('be.enabled','be.enabled')
    })    
    it('TC-AC-003 - Verify that if Currency= SGD and Country = UNITED KINGDOM  & client = EEA and check priority settlement is enabled ', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SGD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('tester SGD')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-004 - Verify that if Currency= SGD and Country = SINGAPORE & Client=EEA with the limit of 200,000 SGD Maximum per payment and check priority and regular both settlement are enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SINGAPORE{enter}' ,'SGD{enter}')
        newRecipient.addBankDetailsWithAccNo('ACLPSGSG','049712')
        newRecipient.individualRecipient('QA Tester SGD')
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('200001','Maximum limit for SGD is 200,000.00')
        newRecipient.checkSettelmentEnabledBoth('be.enabled','be.enabled')
    }) 
    //Currency is MXN
    it('TC-AC-005 - Verify that if Currency= MXN and Country = UK & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'MXN{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Tester MXN')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-006 - Verify that if Currency= MXN and Country = Mexico & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('MEXICO{enter}' ,'MXN{enter}')
        newRecipient.addBankDetailsWithClabe('AFIRMXMT','002010077777777771')
        newRecipient.individualRecipientMexico('QA Tester MXN')
        newRecipient.postCodeState()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-007 - Verify that if Currency= MXN and Country = UK & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'MXN{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Tester MXN')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-008 - Verify that if Currency= MXN and Country = Mexico & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('MEXICO{enter}' ,'MXN{enter}')
        newRecipient.addBankDetailsWithClabe('AFIRMXMT','002010077777777771')
        newRecipient.individualRecipientMexico('QA Tester MXN')
        newRecipient.postCodeState()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-009 - Verify that the CLABE No is requested  if Country = Mexico regardless of currency and Client = UK', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.validateAddRecipient('MEXICO{enter}')
        newRecipient.validateCLABEFeild1('AED{enter}')
        newRecipient.validateCLABEFeild2('AUD{enter}')
        newRecipient.validateCLABEFeild2('CAD{enter}')
        newRecipient.validateCLABEFeild2('CHF{enter}')
        newRecipient.validateCLABEFeild2('CZK{enter}')
        newRecipient.validateCLABEFeild2('DKK{enter}')
        newRecipient.validateCLABEFeild2('EUR{enter}')
        newRecipient.validateCLABEFeild2('GBP{enter}')
        newRecipient.validateCLABEFeild2('HKD{enter}')
        newRecipient.validateCLABEFeild2('HUF{enter}')
        newRecipient.validateCLABEFeild2('JPY{enter}')
        newRecipient.validateCLABEFeild2('KES{enter}')
        newRecipient.validateCLABEFeild2('MXN{enter}')
        newRecipient.validateCLABEFeild2('NOK{enter}')
        newRecipient.validateCLABEFeild2('NZD{enter}')
        newRecipient.validateCLABEFeild2('PLN{enter}')
        newRecipient.validateCLABEFeild2('RON{enter}')
        newRecipient.validateCLABEFeild2('SAR{enter}')
        newRecipient.validateCLABEFeild2('SEK{enter}')
        newRecipient.validateCLABEFeild2('SGD{enter}')
        newRecipient.validateCLABEFeild2('TRY{enter}')
        newRecipient.validateCLABEFeild2('USD{enter}')
        newRecipient.validateCLABEFeild2('ZAR{enter}')
    })
    it('TC-AC-010 - Verify that the CLABE No is requested  if Country = Mexico regardless of currency and Client = EEA', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.validateAddRecipient('MEXICO{enter}')
        newRecipient.validateCLABEFeild1('AED{enter}')
        newRecipient.validateCLABEFeild2('AUD{enter}')
        newRecipient.validateCLABEFeild2('CAD{enter}')
        newRecipient.validateCLABEFeild2('CHF{enter}')
        newRecipient.validateCLABEFeild2('CZK{enter}')
        newRecipient.validateCLABEFeild2('DKK{enter}')
        newRecipient.validateCLABEFeild2('EUR{enter}')
        newRecipient.validateCLABEFeild2('GBP{enter}')
        newRecipient.validateCLABEFeild2('HKD{enter}')
        newRecipient.validateCLABEFeild2('HUF{enter}')
        newRecipient.validateCLABEFeild2('JPY{enter}')
        newRecipient.validateCLABEFeild2('KES{enter}')
        newRecipient.validateCLABEFeild2('MXN{enter}')
        newRecipient.validateCLABEFeild2('NOK{enter}')
        newRecipient.validateCLABEFeild2('NZD{enter}')
        newRecipient.validateCLABEFeild2('PLN{enter}')
        newRecipient.validateCLABEFeild2('RON{enter}')
        newRecipient.validateCLABEFeild2('SAR{enter}')
        newRecipient.validateCLABEFeild2('SEK{enter}')
        newRecipient.validateCLABEFeild2('SGD{enter}')
        newRecipient.validateCLABEFeild2('TRY{enter}')
        newRecipient.validateCLABEFeild2('USD{enter}')
        newRecipient.validateCLABEFeild2('ZAR{enter}')
    })
    //Currency is TRY
    it('TC-AC-011 - Verify that if Currency= TRY and Country = UNITED KINGDOM &  client = UK and check priority settlement is enabled ', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('tester TRY')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-012 - Verify that if Currency= TRY and Country = TURKEY &  Client = UK with the limit of 5,000,000 TRY Maximum per payment and check priority and regular both settlement are enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('TURKEY{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('TR690006245145456117494371','CAYTTRIS002')
        newRecipient.individualRecipient('QA Tester TRY')
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('5000001','Maximum limit for TRY is 5,000,000.00')
        newRecipient.checkSettelmentEnabledBoth('be.enabled','be.enabled')
    })    
    it('TC-AC-013 - Verify that if Currency= TRY and Country = UNITED KINGDOM  & client = EEA and check priority settlement is enabled ', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('tester TRY')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-014 - Verify that if Currency= TRY and Country = TURKEY & Client=EEA with the limit of 5,000,000 TRY Maximum per payment and check priority and regular both settlement are enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('TURKEY{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('TR690006245145456117494371','CAYTTRIS002')
        newRecipient.individualRecipient('QA Tester TRY')
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('5000001','Maximum limit for TRY is 5,000,000.00')
        newRecipient.checkSettelmentEnabledBoth('be.enabled','be.enabled')
    }) 
    //Currency is KWD
    it('TC-AC-015 - Verify that if Currency= KWD and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'KWD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA KWD')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-016 - Verify that if Currency= KWD and Country = Kuwait & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('KUWAIT{enter}' ,'KWD{enter}')
        newRecipient.addBankDetails('KW81CBKU0000000000001234560101','ABKKKWKW')
        newRecipient.individualRecipient('QA KWD')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // currency OMR account no 
    it('TC-AC-017 - Verify that if Currency= OMR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'OMR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test OMR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-018 - Verify that if Currency= OMR and Country = OMAN & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('OMAN{enter}' ,'OMR{enter}')
        newRecipient.addBankDetailsWithAccNo('BDOFOMRUMIB','049712')
        newRecipient.individualRecipient('QA Test OMR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is SAR
    it('TC-AC-019 - Verify that if Currency= SAR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test SAR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-020 - Verify that if Currency= SAR and Country = SAUDI ARABIA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SAUDI ARABIA{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('SA0380000000608010167519','AIASSARI')
        newRecipient.individualRecipient('QA Test SAR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-021 - Verify that if Currency= SAR and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test SAR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-022 - Verify that if Currency= SAR and Country = SAUDI ARABIA & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SAUDI ARABIA{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('SA0380000000608010167519','AIASSARI')
        newRecipient.individualRecipient('QA Test SAR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is QAR
    it('TC-AC-023 - Verify that if Currency= QAR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'QAR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test QAR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-024 - Verify that if Currency= QAR and Country = QATAR & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('QATAR{enter}' ,'QAR{enter}')
        newRecipient.addBankDetails('QA58DOHB00001234567890ABCDEFG','ALZAQAQA')
        newRecipient.individualRecipient('QA Test QAR')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    //Currency is CZK
    it('TC-AC-025 - Verify that if Currency= CZK and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test CZK')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-026 - Verify that if Currency= CZK and Country = Czech Republic & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('Czech Republic{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('CZ5508000000001234567899','AKCNCZP2')
        newRecipient.individualRecipient('QA Test CZK')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-027 - Verify that if Currency= CZK and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test CZK')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-028 - Verify that if Currency= CZK and Country = Czech Republic & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('Czech Republic{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('CZ5508000000001234567899','AKCNCZP2')
        newRecipient.individualRecipient('QA Test CZK')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is RON
    it('TC-AC-029 - Verify that if Currency= RON and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test RON')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-030 - Verify that if Currency= RON and Country = ROMANIA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('ROMANIA{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('RO66BACX0000001234567890','ALBPROBU')
        newRecipient.individualRecipient('QA Test RON')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-031 - Verify that if Currency= RON and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test RON')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-032 - Verify that if Currency= RON and Country = ROMANIA & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('ROMANIA{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('RO66BACX0000001234567890','ALBPROBU')
        newRecipient.individualRecipient('QA Test RON')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // currency is ILS
    it('TC-AC-033 - Verify that if Currency= ILS and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'ILS{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test ILS')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-034 - Verify that if Currency= ILS and Country = ISRAEL & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('ISRAEL{enter}' ,'ILS{enter}')
        newRecipient.addBankDetails('IL170108000000012612345','ASRIILIC')
        newRecipient.individualRecipient('QA Test ILS')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    ////currency is HUF
    it('TC-AC-035 - Verify that if Currency= HUF and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test HUF')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-036 - Verify that if Currency= HUF and Country = HUNGARY & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('HUNGARY{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('HU42117730161111101800000000','AKKHHUHB')
        newRecipient.individualRecipient('QA Test HUF')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-037 - Verify that if Currency= HUF and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test HUF')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-038 - Verify that if Currency= HUF and Country = HUNGARY & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('HUNGARY{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('HU42117730161111101800000000','AKKHHUHB')
        newRecipient.individualRecipient('QA Test HUF')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    ////currency is KES Account No
    it('TC-AC-039 - Verify that if Currency= KES and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'KES{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test KES')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-040 - Verify that if Currency= KES and Country = KENYA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('KENYA{enter}' ,'KES{enter}')
        newRecipient.addBankDetailsWithAccNo('AFRIKENX','049712')
        newRecipient.individualRecipient('QA Test KES')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-041 - Verify that if Currency= KES and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'KES{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test KES')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-042 - Verify that if Currency= KES and Country = KENYA & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('KENYA{enter}' ,'KES{enter}')
        newRecipient.addBankDetailsWithAccNo('AFRIKENX','049712')
        newRecipient.individualRecipient('QA Test KES')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // currency is UGX Account  No
    it('TC-AC-043 - Verify that if Currency= UGX and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'UGX{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('QA Test UGX')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-044 - Verify that if Currency= UGX and Country = UGANDA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UGANDA{enter}' ,'UGX{enter}')
        newRecipient.addBankDetailsWithAccNo('CCEIUGKA','049712')
        newRecipient.individualRecipient('QA Test UGX')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is BHD
    it('TC-AC-045 - Verify that if Currency= BHD and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'BHD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('Test BHD')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-046 - Verify that if Currency= BHD and Country = BAHRAIN & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('BAHRAIN{enter}' ,'BHD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test BHD')
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-047 - Verify that if Country = BAHRAIN regardless of currency & Client = UK and check add recipient journey requies a payment purpose code', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('BAHRAIN{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','AUD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','CAD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','BHD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','CHF{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','CNY{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','CZK{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','DKK{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','EUR{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','GBP{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','HKD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','HUF{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','ILS{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','JPY{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','KES{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','KWD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','MXN{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','NOK{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','NZD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','OMR{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','PLN{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','QAR{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','RON{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','SAR{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','SEK{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','SGD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','THB{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','TRY{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','UGX{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','USD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('BAHRAIN{enter}','ZAR{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
    })
    // Currency is AED
    it('TC-AC-048 - Verify that if Currency= AED and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('Test AED')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-049 - Verify that if Currency= AED and Country = United Arab Emirates & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED ARAB EMIRATES{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test AED')
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-050 - Verify that if Currency= AED and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('Test AED')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-051 - Verify that if Currency= AED and Country = United Arab Emirates & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED ARAB EMIRATES{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test AED')
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-052 - Verify that if Country = United Arab Emirates regardless of currency & Client = UK and check add recipient journey requies a payment purpose code', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED ARAB EMIRATES{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','AUD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','CAD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','BHD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','CHF{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','CNY{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','CZK{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','DKK{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','EUR{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','GBP{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','HKD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','HUF{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','ILS{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','JPY{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','KES{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','KWD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','MXN{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','NOK{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','NZD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','OMR{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','PLN{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','QAR{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','RON{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','SAR{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','SEK{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','SGD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','THB{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','TRY{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','UGX{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','USD{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
        cy.reload()
        newRecipient.selectCurrency('UNITED ARAB EMIRATES{enter}','ZAR{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.individualRecipient('Test')
        newRecipient.validateErrorMsg()
    })
    //Currency is INR
    it('TC-AC-053 - Verify that if Currency= INR and Country = INDIA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('INDIA{downarrow}{enter}' ,'INR{enter}')
        newRecipient.addIndiaBankDetail()
        newRecipient.individualRecipient('Test IND')
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.enabled','be.disabled')
    })
    it('TC-AC-054 - Verify that if Currency= INR and Country = INDIA & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('INDIA{downarrow}{enter}' ,'INR{enter}')
        newRecipient.addIndiaBankDetail()
        newRecipient.individualRecipient('Test IND')
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.enabled','be.disabled')
    })
    // Business Recipient
    // Currency is SAR Business
    it('TC-AC-055 - Verify that if Currency= SAR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-056 - Verify that if Currency= SAR and Country = SAUDI ARABIA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SAUDI ARABIA{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('SA0380000000608010167519','AIASSARI')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-057 - Verify that if Currency= SAR and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-058 - Verify that if Currency= SAR and Country = SAUDI ARABIA & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SAUDI ARABIA{enter}' ,'SAR{enter}')
        newRecipient.addBankDetails('SA0380000000608010167519','AIASSARI')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    //Currency is KWD Business
    it('TC-AC-059 - Verify that if Currency= KWD and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'KWD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-060 - Verify that if Currency= KWD and Country = Kuwait & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('KUWAIT{enter}' ,'KWD{enter}')
        newRecipient.addBankDetails('KW81CBKU0000000000001234560101','ABKKKWKW')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // currency OMR Bussiness
    it('TC-AC-061 - Verify that if Currency= OMR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'OMR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-062 - Verify that if Currency= OMR and Country = OMAN & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('OMAN{enter}' ,'OMR{enter}')
        newRecipient.addBankDetailsWithAccNo('BDOFOMRUMIB','049712')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is QAR Business
    it('TC-AC-063 - Verify that if Currency= QAR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'QAR{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-064 - Verify that if Currency= QAR and Country = QATAR & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('QATAR{enter}' ,'QAR{enter}')
        newRecipient.addBankDetails('QA58DOHB00001234567890ABCDEFG','ALZAQAQA')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    //Currency is CZK Business
    it('TC-AC-065 - Verify that if Currency= CZK and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-066 - Verify that if Currency= CZK and Country = Czech Republic & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('Czech Republic{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('CZ5508000000001234567899','AKCNCZP2')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-067 - Verify that if Currency= CZK and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-068 - Verify that if Currency= CZK and Country = Czech Republic & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('Czech Republic{enter}' ,'CZK{enter}')
        newRecipient.addBankDetails('CZ5508000000001234567899','AKCNCZP2')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is RON Business
    it('TC-AC-069 - Verify that if Currency= RON and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-070 - Verify that if Currency= RON and Country = ROMANIA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('ROMANIA{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('RO66BACX0000001234567890','ALBPROBU')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-071 - Verify that if Currency= RON and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-072 - Verify that if Currency= RON and Country = ROMANIA & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('ROMANIA{enter}' ,'RON{enter}')
        newRecipient.addBankDetails('RO66BACX0000001234567890','ALBPROBU')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // currency is ILS Business
    it('TC-AC-073 - Verify that if Currency= ILS and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'ILS{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-074 - Verify that if Currency= ILS and Country = ISRAEL & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('ISRAEL{enter}' ,'ILS{enter}')
        newRecipient.addBankDetails('IL170108000000012612345','ASRIILIC')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    ////currency is HUF Business
    it('TC-AC-075 - Verify that if Currency= HUF and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-076 - Verify that if Currency= HUF and Country = HUNGARY & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('HUNGARY{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('HU42117730161111101800000000','AKKHHUHB')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-077 - Verify that if Currency= HUF and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-078 - Verify that if Currency= HUF and Country = HUNGARY & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('HUNGARY{enter}' ,'HUF{enter}')
        newRecipient.addBankDetails('HU42117730161111101800000000','AKKHHUHB')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    //currency is KES Business
    it('TC-AC-079 - Verify that if Currency= KES and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'KES{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-080 - Verify that if Currency= KES and Country = KENYA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('KENYA{enter}' ,'KES{enter}')
        newRecipient.addBankDetailsWithAccNo('AFRIKENX','049712')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-081 - Verify that if Currency= KES and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'KES{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-082 - Verify that if Currency= KES and Country = KENYA & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('KENYA{enter}' ,'KES{enter}')
        newRecipient.addBankDetailsWithAccNo('AFRIKENX','049712')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // currency is UGX Business
    it('TC-AC-083 - Verify that if Currency= UGX and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'UGX{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-084 - Verify that if Currency= UGX and Country = UGANDA & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UGANDA{enter}' ,'UGX{enter}')
        newRecipient.addBankDetailsWithAccNo('CCEIUGKA','049712')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is BHD
    it('TC-AC-085 - Verify that if Currency= BHD and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'BHD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-086 - Verify that if Currency= BHD and Country = BAHRAIN & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('BAHRAIN{enter}' ,'BHD{enter}')
        newRecipient.addBankDetails('BH67BMAG00001299123456','ABBGBHBM')
        newRecipient.addBusinessRecipient()
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is AED
    it('TC-AC-087 - Verify that if Currency= AED and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-088 - Verify that if Currency= AED and Country = United Arab Emirates & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED ARAB EMIRATES{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.addBusinessRecipient()
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-089 - Verify that if Currency= AED and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-090 - Verify that if Currency= AED and Country = United Arab Emirates & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED ARAB EMIRATES{enter}' ,'AED{enter}')
        newRecipient.addBankDetails('AE070331234567890123456','AARPAEAA')
        newRecipient.addBusinessRecipient()
        newRecipient.paymentPurpose()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    //Currency is MXN Business
    it('TC-AC-091 - Verify that if Currency= MXN and Country = UK & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'MXN{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-092 - Verify that if Currency= MXN and Country = Mexico & Client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('MEXICO{enter}' ,'MXN{enter}')
        newRecipient.addBankDetailsWithClabe('AFIRMXMT','002010077777777771')
        newRecipient.addBusinessRecipient()
        newRecipient.postCodeState()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-093 - Verify that if Currency= MXN and Country = UK & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'MXN{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-094 - Verify that if Currency= MXN and Country = Mexico & Client = EEA and check priority settlement is enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('MEXICO{enter}' ,'MXN{enter}')
        newRecipient.addBankDetailsWithClabe('AFIRMXMT','002010077777777771')
        newRecipient.addBusinessRecipient()
        newRecipient.postCodeState()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    // Currency is SGD Business
    it('TC-AC-095 - Verify that if Currency= SGD and Country = UNITED KINGDOM & client = UK and check priority settlement is enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SGD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-096 - Verify that if Currency= SGD and Country = SINGAPORE  & Client = UK with the limit of 200,000 SGD Maximum per payment and check priority and regular both settlement are enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SINGAPORE{enter}' ,'SGD{enter}')
        newRecipient.addBankDetailsWithAccNo('ACLPSGSG','049712')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('200001','Maximum limit for SGD is 200,000.00')
        newRecipient.checkSettelmentEnabledBoth('be.enabled','be.enabled')
    })    
    it('TC-AC-097 - Verify that if Currency= SGD and Country = UNITED KINGDOM  & client = EEA and check priority settlement is enabled ', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'SGD{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-098 - Verify that if Currency= SGD and Country = SINGAPORE & Client=EEA with the limit of 200,000 SGD Maximum per payment and check priority and regular both settlement are enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('SINGAPORE{enter}' ,'SGD{enter}')
        newRecipient.addBankDetailsWithAccNo('ACLPSGSG','049712')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('200001','Maximum limit for SGD is 200,000.00')
        newRecipient.checkSettelmentEnabledBoth('be.enabled','be.enabled')
    })
    //Currency is TRY
    it('TC-AC-099 - Verify that if Currency= TRY and Country = UNITED KINGDOM &  client = UK and check priority settlement is enabled ', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-100 - Verify that if Currency= TRY and Country = TURKEY &  Client = UK with the limit of 5,000,000 TRY Maximum per payment and check priority settlement enabled', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('TURKEY{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('TR690006245145456117494371','CAYTTRIS002')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('5000001','Maximum limit for TRY is 5,000,000.00')
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })    
    it('TC-AC-101 - Verify that if Currency= TRY and Country = UNITED KINGDOM  & client = EEA and check priority settlement is enabled ', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('UNITED KINGDOM{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    it('TC-AC-102 - Verify that if Currency= TRY and Country = TURKEY & Client=EEA with the limit of 5,000,000 TRY Maximum per payment and check priority and regular both settlement are enabled', function(){
        signin.Login('carmenTestingBWA3@gmail.com', password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('TURKEY{enter}' ,'TRY{enter}')
        newRecipient.addBankDetails('TR690006245145456117494371','CAYTTRIS002')
        newRecipient.addBusinessRecipient()
        newRecipient.saveRecipient()
        newRecipient.checkAmountLimit('5000001','Maximum limit for TRY is 5,000,000.00')
        newRecipient.checkSettelmentEnabledBoth('be.enabled','be.enabled')
    })  
    // most important scenarios by carmen
    xit('TC-AC-103 - Verify that payments to the recipients without ABA code with currency USD & country US should have only priority Settlement Method enabled.', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('United states{enter}' ,'USD{enter}')
        newRecipient.addBankDetailsWithAccNo('MMMCUS44','55555555')
        newRecipient.individualRecipientMexico('QA USA TO USD')
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    xit('TC-AC-104 - Verify that payments to the recipients with ABA code with currency USD & country US should have only priority Settlement Method enabled.', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('United states{enter}' ,'USD{enter}')
        newRecipient.addBankDetailsWithAccNo('MMMCUS44','55555555')
        cy.get('#aba').type('026009593')
        newRecipient.individualRecipientMexico('QA USA TO USD')
        newRecipient.postCodeState()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    xit('TC-AC-105 - Verify that payments to the recipients with ABA code with country US & currency Euro should have only priority Settlement Method enabled.', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('United states{enter}' ,'EUR{enter}')
        newRecipient.addBankDetailsWithAccNo('MMMCUS44','55555555')
        cy.get('#aba').type('026009593')
        newRecipient.individualRecipientMexico('QA USA TO USD')
        newRecipient.postCodeState()
        newRecipient.saveRecipient()
        newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    xit('TC-AC-106 - Verify that payments to the recipients without ABA code with currency USD & country US should have only priority Settlement Method enabled.', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('United states{enter}' ,'EUR{enter}')
        newRecipient.addBankDetailsWithAccNo('MMMCUS44','55555555')
        newRecipient.individualRecipientMexico('QA USA TO USD')
        // newRecipient.saveRecipient()
        // newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    xit('TC-AC-107 -Verify that if Currency= GBP and Country = United kingdom', function(){
        signin.Login(userName, password)
        newRecipient.goToPaymentsDashborad()
        newRecipient.gotoRecipientList()
        newRecipient.addRecipient('United kingdom{enter}' ,'GBP{enter}')
        newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
        newRecipient.individualRecipient('Test GBP to UK')
        newRecipient.saveRecipient()
        //newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    xit('TC-AC-108 -Verify that if Currency= USD and Country = United kingdom', function(){
    signin.Login(userName, password)
    newRecipient.goToPaymentsDashborad()
    newRecipient.gotoRecipientList()
    newRecipient.addRecipient('United kingdom{enter}' ,'USD{enter}')
    newRecipient.addBankDetails('GB73BARC20039538243547','AFFLGB22')
    newRecipient.individualRecipient('Test USD to UK')
    newRecipient.saveRecipient()
    //newRecipient.checkSettelment('be.disabled','be.enabled')
    })
    xit('TC-AC-109 -Verify that if Currency= CNY and Country = China', function(){
    signin.Login(userName, password)
    newRecipient.goToPaymentsDashborad()
    newRecipient.gotoRecipientList()
    newRecipient.addRecipient('China{enter}' ,'CNY{enter}')
    newRecipient.addBankDetailsWithAccNo('AYCLCNBY','55555555')
    newRecipient.individualRecipient('Test CNY to china')
    newRecipient.paymentPurpose()
    newRecipient.saveRecipient()
    //newRecipient.checkSettelment('be.disabled','be.enabled')
    })
})