name: Volopa e2e Test

on:
  # Manual Button Click from Github UI
  workflow_dispatch:
  # Uncomment this if you want to run it on master push
  # push:
  #   branches: [ master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          spec: |
            cypress/e2e/recipientList.cy.js
            cypress/e2e/paymentsHistory.cy.js
            cypress/e2e/paymentsDashboard.cy.js
            
      - name: Upload HTML Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 7
